<dec f='codebrowser/gtsam/linear/tests/testSerializationLinear.cpp' l='39' macro='1' type='const guid_initializer&lt;gtsam::noiseModel::Constrained&gt; &amp;'/>
<def f='codebrowser/gtsam/linear/tests/testSerializationLinear.cpp' l='39' macro='1' type='const guid_initializer&lt;gtsam::noiseModel::Constrained&gt; &amp;'/>
<dec f='codebrowser/gtsam/navigation/tests/testSerializationNavigation.cpp' l='35' macro='1' type='const guid_initializer&lt;noiseModel::Constrained&gt; &amp;'/>
<def f='codebrowser/gtsam/navigation/tests/testSerializationNavigation.cpp' l='35' macro='1' type='const guid_initializer&lt;noiseModel::Constrained&gt; &amp;'/>
<dec f='codebrowser/gtsam/nonlinear/tests/testSerializationNonlinear.cpp' l='43' macro='1' type='const guid_initializer&lt;gtsam::noiseModel::Constrained&gt; &amp;'/>
<def f='codebrowser/gtsam/nonlinear/tests/testSerializationNonlinear.cpp' l='43' macro='1' type='const guid_initializer&lt;gtsam::noiseModel::Constrained&gt; &amp;'/>
<dec f='codebrowser/gtsam/slam/tests/testSerializationInSlam.cpp' l='38' macro='1' type='const guid_initializer&lt;noiseModel::Constrained&gt; &amp;'/>
<def f='codebrowser/gtsam/slam/tests/testSerializationInSlam.cpp' l='38' macro='1' type='const guid_initializer&lt;noiseModel::Constrained&gt; &amp;'/>
<dec f='codebrowser/tests/testSerializationSlam.cpp' l='126' macro='1' type='const guid_initializer&lt;gtsam::noiseModel::Constrained&gt; &amp;'/>
<def f='codebrowser/tests/testSerializationSlam.cpp' l='126' macro='1' type='const guid_initializer&lt;gtsam::noiseModel::Constrained&gt; &amp;'/>
