<use f='include/boost/phoenix/bind/detail/member_variable.hpp' l='47' u='w' c='_ZN5boost7phoenix6detail15member_variableC1ET0_'/>
<use f='include/boost/phoenix/bind/detail/member_variable.hpp' l='55' u='r' c='_ZNK5boost7phoenix6detail15member_variableclERTL0__'/>
<use f='include/boost/phoenix/bind/detail/member_variable.hpp' l='61' u='r' c='_ZNK5boost7phoenix6detail15member_variableclEPTL0__'/>
<use f='include/boost/phoenix/bind/detail/member_variable.hpp' l='70' u='r' c='_ZNK5boost7phoenix6detail15member_variableclERKTL0__'/>
<use f='include/boost/phoenix/bind/detail/member_variable.hpp' l='76' u='r' c='_ZNK5boost7phoenix6detail15member_variableclEPKTL0__'/>
<dec f='include/boost/phoenix/bind/detail/member_variable.hpp' l='79' type='MP'/>
