<def f='codebrowser/gtsam/linear/tests/testNoiseModel.cpp' l='207' ll='211' type='Matrix'/>
<use f='codebrowser/gtsam/linear/tests/testNoiseModel.cpp' l='227' u='r' c='_ZN16NoiseModelQRTest3runER10TestResult'/>
<use f='codebrowser/gtsam/linear/tests/testNoiseModel.cpp' l='228' u='r' c='_ZN16NoiseModelQRTest3runER10TestResult'/>
<doc f='codebrowser/gtsam/linear/tests/testNoiseModel.cpp' l='206'>// create a matrix to eliminate</doc>
