<def f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='167' type='Vector3'/>
<use f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='173' u='r'/>
<use f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='174' u='r'/>
<use f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='188' u='r' c='_ZN22AdaptAutoDiffLocalTest3runER10TestResult'/>
<use f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='198' u='r' c='_ZN26AdaptAutoDiffAutoDiff2Test3runER10TestResult'/>
<use f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='207' u='m' c='_ZN26AdaptAutoDiffAutoDiff2Test3runER10TestResult'/>
<use f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='224' u='r' c='_ZN30AdaptAutoDiffAdaptAutoDiffTest3runER10TestResult'/>
<use f='codebrowser/gtsam/nonlinear/tests/testAdaptAutoDiff.cpp' l='230' u='r' c='_ZN30AdaptAutoDiffAdaptAutoDiffTest3runER10TestResult'/>
