<def f='codebrowser/gtsam/slam/tests/testEssentialMatrixFactor.cpp' l='594' type='std::shared_ptr&lt;Cal3Bundler&gt;'/>
<use f='codebrowser/gtsam/slam/tests/testEssentialMatrixFactor.cpp' l='612' u='a' c='_ZN8example242EssentialMatrixFactorextraMinimizationTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testEssentialMatrixFactor.cpp' l='651' u='r' c='_ZN8example235EssentialMatrixFactor2extraTestTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testEssentialMatrixFactor.cpp' l='678' u='a' c='_ZN8example243EssentialMatrixFactor2extraMinimizationTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testEssentialMatrixFactor.cpp' l='711' u='r' c='_ZN8example235EssentialMatrixFactor3extraTestTest3runER10TestResult'/>
