<def f='codebrowser/gtsam/basis/Basis.h' l='294' type='const auto'/>
<use f='codebrowser/gtsam/basis/Basis.h' l='302' u='r' c='_ZN5gtsam5Basis25ManifoldEvaluationFunctorC1Emd'/>
<use f='codebrowser/gtsam/basis/Basis.h' l='306' u='r' c='_ZN5gtsam5Basis25ManifoldEvaluationFunctorC1Emddd'/>
<use f='codebrowser/gtsam/basis/Basis.h' l='311' c='_ZNK5gtsam5Basis25ManifoldEvaluationFunctor5applyERKN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS_16OptionalJacobianILin1ELin1EEE'/>
<use f='codebrowser/gtsam/basis/Basis.h' l='314' c='_ZNK5gtsam5Basis25ManifoldEvaluationFunctor5applyERKN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS_16OptionalJacobianILin1ELin1EEE'/>
<use f='codebrowser/gtsam/basis/Basis.h' l='314' c='_ZNK5gtsam5Basis25ManifoldEvaluationFunctor5applyERKN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS_16OptionalJacobianILin1ELin1EEE'/>
