<def f='codebrowser/gtsam/slam/KarcherMeanFactor.h' l='52' type='const auto'/>
<use f='codebrowser/gtsam/slam/KarcherMeanFactor.h' l='67' c='_ZN5gtsam17KarcherMeanFactorC1ERKTL0__iSt8optionalIdE'/>
<use f='codebrowser/gtsam/slam/KarcherMeanFactor.h' l='67' c='_ZN5gtsam17KarcherMeanFactorC1ERKTL0__iSt8optionalIdE'/>
<doc f='codebrowser/gtsam/slam/KarcherMeanFactor.h' l='51'>// Compile time dimension: can be -1</doc>
