<dec f='codebrowser/gtsam/geometry/Kernel.h' l='59' type='const DexpFunctor *'/>
<offset>0</offset>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='106' u='r' c='_ZNK5gtsam3so310InvJKernel4leftEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='113' u='r' c='_ZNK5gtsam3so310InvJKernel4leftEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='113' u='r' c='_ZNK5gtsam3so310InvJKernel4leftEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='113' u='r' c='_ZNK5gtsam3so310InvJKernel4leftEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='116' u='r' c='_ZNK5gtsam3so310InvJKernel5rightEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='119' u='r' c='_ZNK5gtsam3so310InvJKernel5rightEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='119' u='r' c='_ZNK5gtsam3so310InvJKernel5rightEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='119' u='r' c='_ZNK5gtsam3so310InvJKernel5rightEv'/>
