<dec f='codebrowser/examples/ABC.h' l='199' type='std::array&lt;Rot3, N&gt;'/>
<use f='codebrowser/examples/ABC.h' l='204' u='w' c='_ZN5gtsam11abc_eqf_lib1GC1ERKNS_4Rot3ERKN5Eigen6MatrixIdLi3ELi3ELi0ELi3ELi3EEERKSt5arrayIS2_XT_EE'/>
<use f='codebrowser/examples/ABC.h' l='210' c='_ZNK5gtsam11abc_eqf_lib1GmlERKNS0_1GIXT_EEE'/>
<use f='codebrowser/examples/ABC.h' l='220' u='c' c='_ZNK5gtsam11abc_eqf_lib1G3invEv'/>
<doc f='codebrowser/examples/ABC.h' l='199'>/// List of SO(3) elements for calibration</doc>
