<dec f='codebrowser/gtsam/geometry/Kernel.h' l='60' type='Kernel'/>
<offset>64</offset>
<doc f='codebrowser/gtsam/geometry/Kernel.h' l='60'>// holds the forward kernel</doc>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='110' u='m' c='_ZNK5gtsam3so310InvJKernel4leftEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='117' u='m' c='_ZNK5gtsam3so310InvJKernel5rightEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='128' u='m' c='_ZNK5gtsam3so310InvJKernel9applyLeftERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEENS_16OptionalJacobianILi3ELi3EEES8_'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='141' u='m' c='_ZNK5gtsam3so310InvJKernel10applyRightERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEENS_16OptionalJacobianILi3ELi3EEES8_'/>
