<dec f='codebrowser/gtsam/geometry/Kernel.h' l='39' type='const DexpFunctor *'/>
<offset>0</offset>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='56' u='r' c='_ZNK5gtsam3so36Kernel4leftEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='56' u='r' c='_ZNK5gtsam3so36Kernel4leftEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='60' u='r' c='_ZNK5gtsam3so36Kernel5rightEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='60' u='r' c='_ZNK5gtsam3so36Kernel5rightEv'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='65' u='r' c='_ZNK5gtsam3so36Kernel9applyLeftERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEENS_16OptionalJacobianILi3ELi3EEES8_'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='66' u='r' c='_ZNK5gtsam3so36Kernel9applyLeftERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEENS_16OptionalJacobianILi3ELi3EEES8_'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='69' u='r' c='_ZNK5gtsam3so36Kernel9applyLeftERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEENS_16OptionalJacobianILi3ELi3EEES8_'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='84' u='r' c='_ZNK5gtsam3so36Kernel10applyRightERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEENS_16OptionalJacobianILi3ELi3EEES8_'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='89' u='r' c='_ZNK5gtsam3so36Kernel7frechetERKN5Eigen6MatrixIdLi3ELi3ELi0ELi3ELi3EEE'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='90' u='r' c='_ZNK5gtsam3so36Kernel7frechetERKN5Eigen6MatrixIdLi3ELi3ELi0ELi3ELi3EEE'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='149' u='r' c='_ZN5gtsam3so34axpyEdRKNS0_6KernelES3_'/>
<use f='codebrowser/gtsam/geometry/Kernel.cpp' l='161' u='r' c='_ZN5gtsam3so35blendEddRKNS0_6KernelES3_'/>
