<def f='codebrowser/gtsam/base/Matrix.h' l='463' type='const auto'/>
<use f='codebrowser/gtsam/base/Matrix.h' l='470'/>
<use f='codebrowser/gtsam/base/Matrix.h' l='478' c='_ZNK5gtsam27MultiplyWithInverseFunctionclERKT_RKN5Eigen6MatrixIdXT0_ELi1EXorLNS4_14StorageOptionsE0EquaaeqT0_Li1EneLi1ELi1ELS6_1EquaaeqLi1ELi1EneT0_Li14568320'/>
<use f='codebrowser/gtsam/base/Matrix.h' l='486' c='_ZNK5gtsam27MultiplyWithInverseFunctionclERKT_RKN5Eigen6MatrixIdXT0_ELi1EXorLNS4_14StorageOptionsE0EquaaeqT0_Li1EneLi1ELi1ELS6_1EquaaeqLi1ELi1EneT0_Li14568320'/>
