<dec f='codebrowser/gtsam/geometry/CameraSet.h' l='48' type='const int'/>
<use f='codebrowser/gtsam/geometry/CameraSet.h' l='78' u='r'/>
<use f='codebrowser/gtsam/geometry/CameraSet.h' l='415' u='r' c='_ZN5gtsam9CameraSet21UpdateSchurComplementERKSt6vectorIN5Eigen6MatrixIdL_ZNS0_4ZDimEEL_ZNS0_1DEEXorLNS2_14StorageOptionsE0EquaaeqL_ZNS0_4ZDimEELi1EneL2171084'/>
<def f='codebrowser/gtsam/geometry/CameraSet.h' l='488' ll='489' type='const int'/>
<def f='codebrowser/gtsam/geometry/CameraSet.h' l='489' type='const int'/>
<def f='codebrowser/gtsam/geometry/CameraSet.h' l='489' type='const int'/>
<def f='codebrowser/gtsam/geometry/CameraSet.h' l='489' type='const int'/>
<def f='codebrowser/gtsam/geometry/CameraSet.h' l='489' type='const int'/>
<doc f='codebrowser/gtsam/geometry/CameraSet.h' l='48'>///&lt; Camera dimension</doc>
