<dec f='codebrowser/gtsam/geometry/SO3.h' l='146' type='double'/>
<offset>1408</offset>
<doc f='codebrowser/gtsam/geometry/SO3.h' l='146'>// B = (1 - cos(theta))</doc>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='86' u='w' c='_ZN5gtsam3so313ExpmapFunctor4initEd'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='90' u='w' c='_ZN5gtsam3so313ExpmapFunctor4initEd'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='113' u='r' c='_ZNK5gtsam3so313ExpmapFunctor6expmapEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='137' u='r' c='_ZNK5gtsam3so311DexpFunctor1DEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='145' u='r' c='_ZNK5gtsam3so311DexpFunctor1EEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='154' u='r' c='_ZNK5gtsam3so311DexpFunctor2dAEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='162' u='r' c='_ZNK5gtsam3so311DexpFunctor2dBEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='169' u='r' c='_ZNK5gtsam3so311DexpFunctor2dCEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='183' u='r' c='_ZNKR5gtsam3so311DexpFunctor9RodriguesEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='184' u='r' c='_ZNKR5gtsam3so311DexpFunctor8JacobianEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='189' u='r' c='_ZNK5gtsam3so311DexpFunctor13rightJacobianEv'/>
<use f='codebrowser/gtsam/geometry/SO3.cpp' l='190' u='r' c='_ZNK5gtsam3so311DexpFunctor12leftJacobianEv'/>
<use f='codebrowser/gtsam/geometry/Similarity3.cpp' l='258' u='r' c='_ZN5gtsam12_GLOBAL__N_16LocalV8compute_Ev'/>
<use f='codebrowser/gtsam/geometry/Similarity3.cpp' l='268' u='r' c='_ZNK5gtsam12_GLOBAL__N_16LocalV6kernelEv'/>
