<dec f='codebrowser/gtsam/slam/SmartFactorBase.h' l='86' type='FBlocks'/>
<use f='codebrowser/gtsam/slam/SmartFactorBase.h' l='104' u='w' c='_ZN5gtsam15SmartFactorBaseC1ERKSt10shared_ptrINS_10noiseModel4BaseEESt8optionalINS_5Pose3EEm'/>
<use f='codebrowser/gtsam/slam/SmartFactorBase.h' l='357' c='_ZNK5gtsam15SmartFactorBase19createHessianFactorERKNS_9CameraSetIT_EERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEEdb'/>
<use f='codebrowser/gtsam/slam/SmartFactorBase.h' l='360' c='_ZNK5gtsam15SmartFactorBase19createHessianFactorERKNS_9CameraSetIT_EERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEEdb'/>
<use f='codebrowser/gtsam/slam/SmartFactorBase.h' l='377' c='_ZNK5gtsam15SmartFactorBase22updateAugmentedHessianERKNS_9CameraSetIT_EERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEEdbRNS_20SymmetricBlockMatrixESt6vectorImSaImEE'/>
<use f='codebrowser/gtsam/slam/SmartFactorBase.h' l='378' c='_ZNK5gtsam15SmartFactorBase22updateAugmentedHessianERKNS_9CameraSetIT_EERKN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEEdbRNS_20SymmetricBlockMatrixESt6vectorImSaImEE'/>
<doc f='codebrowser/gtsam/slam/SmartFactorBase.h' l='85'>// Cache for Fblocks, to avoid a malloc ever time we re-linearize</doc>
