<def f='codebrowser/gtsam/sfm/tests/testShonanFactor.cpp' l='43' type='SO3'/>
<use f='codebrowser/gtsam/sfm/tests/testShonanFactor.cpp' l='44' u='r'/>
<def f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='47' type='SO3'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='48' u='r'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='54' u='m' c='_ZN34FrobeniusPriorSO3EvaluateErrorTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='56' u='m' c='_ZN34FrobeniusPriorSO3EvaluateErrorTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='115' u='r' c='_ZN35FrobeniusFactorSO3EvaluateErrorTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='116' u='m' c='_ZN35FrobeniusFactorSO3EvaluateErrorTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='121' u='r' c='_ZN35FrobeniusFactorSO3EvaluateErrorTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='146' u='r' c='_ZN42FrobeniusBetweenFactorSO3EvaluateErrorTest3runER10TestResult'/>
<use f='codebrowser/gtsam/slam/tests/testFrobeniusFactor.cpp' l='152' u='r' c='_ZN42FrobeniusBetweenFactorSO3EvaluateErrorTest3runER10TestResult'/>
