<def f='codebrowser/gtsam/sfm/tests/testShonanFactor.cpp' l='54' type='SO3'/>
<use f='codebrowser/gtsam/sfm/tests/testShonanFactor.cpp' l='56' u='r'/>
<use f='codebrowser/gtsam/sfm/tests/testShonanFactor.cpp' l='66' u='m' c='_ZN30ShonanFactor3evaluateErrorTest3runER10TestResult'/>
<use f='codebrowser/gtsam/sfm/tests/testShonanFactor.cpp' l='87' u='r' c='_ZN33ShonanFactor3equivalenceToSO3Test3runER10TestResult'/>
