<def f='codebrowser/gtsam/nonlinear/tests/testExpression.cpp' l='215' type='Expression&lt;Cal3_S2&gt;'/>
<use f='codebrowser/gtsam/nonlinear/tests/testExpression.cpp' l='220' u='r'/>
<use f='codebrowser/gtsam/nonlinear/tests/testExpression.cpp' l='248' u='m' c='_ZN27ExpressionTreeTraceSizeTest3runER10TestResult'/>
<use f='codebrowser/gtsam/nonlinear/tests/testExpression.cpp' l='251' u='m' c='_ZN27ExpressionTreeTraceSizeTest3runER10TestResult'/>
<doc f='codebrowser/gtsam/nonlinear/tests/testExpression.cpp' l='214'>// Create leaves</doc>
