<dec f='codebrowser/gtsam/3rdparty/metis/libmetis/struct.h' l='62' type='idx_t'/>
<offset>32</offset>
<doc f='codebrowser/gtsam/3rdparty/metis/libmetis/struct.h' l='62'>/*!&lt; The total external degree of a vertex (count of edges) */</doc>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/contig.c' l='627' u='r' c='libmetis__MoveGroupContigForVol'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/debug.c' l='371' u='w' c='libmetis__CheckKWayVolPartitionParams'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/debug.c' l='371' u='r' c='libmetis__CheckKWayVolPartitionParams'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='526' u='r' c='libmetis__Greedy_KWayVolOptimize'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='1199' u='r' c='libmetis__Greedy_McKWayVolOptimize'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='1531' u='w' c='libmetis__KWayVolUpdate'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='1560' u='w' c='libmetis__KWayVolUpdate'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='1563' u='w' c='libmetis__KWayVolUpdate'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='1801' u='r' c='libmetis__KWayVolUpdate'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='1816' u='r' c='libmetis__KWayVolUpdate'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayfm.c' l='1819' u='r' c='libmetis__KWayVolUpdate'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayrefine.c' l='265' u='w' c='libmetis__ComputeKWayPartitionParams'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayrefine.c' l='269' u='r' c='libmetis__ComputeKWayPartitionParams'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayrefine.c' l='270' u='r' c='libmetis__ComputeKWayPartitionParams'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayrefine.c' l='431' u='r' c='libmetis__ProjectKWayPartition'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayrefine.c' l='470' u='w' c='libmetis__ProjectKWayPartition'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayrefine.c' l='545' u='r' c='libmetis__ComputeKWayBoundary'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/kwayrefine.c' l='650' u='r' c='libmetis__ComputeKWayVolGains'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/minconn.c' l='79' u='r' c='libmetis__ComputeSubDomainGraph'/>
<use f='codebrowser/gtsam/3rdparty/metis/libmetis/minconn.c' l='586' u='r' c='libmetis__MoveGroupMinConnForVol'/>
